FROM pytorch/pytorch:latest

RUN pip install uvicorn && \
    pip install fastapi


EXPOSE 5001

COPY ../transformers \
     /root/transformers

WORKDIR /root/transformers

RUN python ./setup.py  develop && \


CMD [ "python" , "/root/src/transformers/commands/mod_serving_multi.py", \
      "--host",  "0.0.0.0", \
      "--port" ,"5001" , \
      "--workers","36" ]

