FROM pytorch/pytorch:latest

RUN pip install uvicorn && \
    pip install fastapi


EXPOSE 5001

WORKDIR /root

RUN git clone -b multi-process-serve --single-branch https://github.com/zhoudoufu/transformers.git && \
    cd transformers

WORKDIR /root/transformers

RUN python ./setup.py  develop

CMD [ "python" , "./src/transformers/commands/mod_serving_multi.py", \
      "--host",  "0.0.0.0", \
      "--port" ,"5001" , \
      "--workers","36" ]

